apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: ZFhObGNtNWhiV1VL #dXNlcm5hbWUK 
    mongo-root-password: VUVCemMzY3djbVFoQ2c9PQo= #UEBzc3cwcmQhCg==

